apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-app
      env: dev
  template:
    metadata:
      labels:
        app: frontend-app
        env: dev
    spec:
      containers:
        - name: frontend-container
          image: localhost:5000/frontend-ms
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: SERVICE_BACKEND1
              value: "api/message"
